[build]
base = "."
command = "CI= npm run build"
publish = "./build/"

[[redirects]]
  from = "/cotovia"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404